// AUTO-GENERATED by scripts/gen-map-assets — do not hand-edit. Re-run after asset changes.
import layout from './03-lakeside-retreat/map/layout.json';

export const groundImage = require('./03-lakeside-retreat/map/ground.png');
export const waterFullMapFrames = [
  require('./03-lakeside-retreat/animations/water/full-map/frame-00.png'),
  require('./03-lakeside-retreat/animations/water/full-map/frame-01.png'),
  require('./03-lakeside-retreat/animations/water/full-map/frame-02.png'),
  require('./03-lakeside-retreat/animations/water/full-map/frame-03.png'),
  require('./03-lakeside-retreat/animations/water/full-map/frame-04.png'),
  require('./03-lakeside-retreat/animations/water/full-map/frame-05.png'),
  require('./03-lakeside-retreat/animations/water/full-map/frame-06.png'),
  require('./03-lakeside-retreat/animations/water/full-map/frame-07.png'),
];
export const grassSheet = require('./03-lakeside-retreat/animations/grass/sheet.png');
export const reedsSheet = require('./03-lakeside-retreat/animations/reeds/sheet.png');

export const propImages: Record<string, number> = {
  'cottage-01': require('./03-lakeside-retreat/props/cottage-01.png'),
  'cottage-02': require('./03-lakeside-retreat/props/cottage-02.png'),
  'tree-01': require('./03-lakeside-retreat/props/tree-01.png'),
  'tree-02': require('./03-lakeside-retreat/props/tree-02.png'),
  'tree-03': require('./03-lakeside-retreat/props/tree-03.png'),
  'tree-04': require('./03-lakeside-retreat/props/tree-04.png'),
  'tree-05': require('./03-lakeside-retreat/props/tree-05.png'),
  'tree-06': require('./03-lakeside-retreat/props/tree-06.png'),
  'tree-07': require('./03-lakeside-retreat/props/tree-07.png'),
  'tree-08': require('./03-lakeside-retreat/props/tree-08.png'),
  'tree-09': require('./03-lakeside-retreat/props/tree-09.png'),
  'tree-10': require('./03-lakeside-retreat/props/tree-10.png'),
  'bush-01': require('./03-lakeside-retreat/props/bush-01.png'),
  'bench-01': require('./03-lakeside-retreat/props/bench-01.png'),
  'flowerbed-01': require('./03-lakeside-retreat/props/flowerbed-01.png'),
  'flowerbed-02': require('./03-lakeside-retreat/props/flowerbed-02.png'),
  'flowerbed-03': require('./03-lakeside-retreat/props/flowerbed-03.png'),
  'sign-01': require('./03-lakeside-retreat/props/sign-01.png'),
  'sign-02': require('./03-lakeside-retreat/props/sign-02.png'),
  'water-bowl-01': require('./03-lakeside-retreat/props/water-bowl-01.png'),
  'fence-01': require('./03-lakeside-retreat/props/fence-01.png'),
  'fence-02': require('./03-lakeside-retreat/props/fence-02.png'),
  'bridge-01': require('./03-lakeside-retreat/props/bridge-01.png'),
  'bridge-02': require('./03-lakeside-retreat/props/bridge-02.png'),
};

export const mapManifest = {
  "name": "03-lakeside-retreat",
  "title": "물가 쉼터",
  "version": "1.0.0",
  "mapWidth": 640,
  "mapHeight": 640,
  "coordinates": "top-left, world pixels, y increases down",
  "pixelScale": 2,
  "sampling": "nearest",
  "layout": "map/layout.json",
  "ground": "map/ground.png",
  "sceneryAtlas": "map/scenery-atlas.png",
  "plantsAtlas": "animations/plants-atlas.png",
  "tilemap": "map/ground-tilemap.json",
  "drawOrder": [
    "ground",
    "masked water",
    "plants",
    "objects and actors sorted by depth",
    "labels and UI"
  ],
  "animations": {
    "water": {
      "frameWidth": 32,
      "frameHeight": 32,
      "frameCount": 8,
      "frameDurationMs": 250,
      "row": 0,
      "direction": "right",
      "sheet": "animations/water/sheet.png",
      "mask": "map/water-mask.png",
      "fullMapFrames": [
        "animations/water/full-map/frame-00.png",
        "animations/water/full-map/frame-01.png",
        "animations/water/full-map/frame-02.png",
        "animations/water/full-map/frame-03.png",
        "animations/water/full-map/frame-04.png",
        "animations/water/full-map/frame-05.png",
        "animations/water/full-map/frame-06.png",
        "animations/water/full-map/frame-07.png"
      ]
    },
    "grass": {
      "frameWidth": 24,
      "frameHeight": 24,
      "frameCount": 8,
      "frameDurationMs": 250,
      "row": 0,
      "anchorX": 12,
      "anchorY": 20,
      "sheet": "animations/grass/sheet.png",
      "combinedAtlasRow": 0
    },
    "reeds": {
      "frameWidth": 24,
      "frameHeight": 24,
      "frameCount": 8,
      "frameDurationMs": 250,
      "row": 0,
      "anchorX": 12,
      "anchorY": 20,
      "sheet": "animations/reeds/sheet.png",
      "combinedAtlasRow": 1
    }
  },
  "props": [
    {
      "id": "cottage-01",
      "file": "props/cottage-01.png",
      "width": 144,
      "height": 152,
      "atlasRect": {
        "x": 0,
        "y": 0,
        "w": 144,
        "h": 152
      }
    },
    {
      "id": "cottage-02",
      "file": "props/cottage-02.png",
      "width": 76,
      "height": 88,
      "atlasRect": {
        "x": 148,
        "y": 0,
        "w": 76,
        "h": 88
      }
    },
    {
      "id": "tree-01",
      "file": "props/tree-01.png",
      "width": 50,
      "height": 90,
      "atlasRect": {
        "x": 228,
        "y": 0,
        "w": 50,
        "h": 90
      }
    },
    {
      "id": "tree-02",
      "file": "props/tree-02.png",
      "width": 68,
      "height": 88,
      "atlasRect": {
        "x": 282,
        "y": 0,
        "w": 68,
        "h": 88
      }
    },
    {
      "id": "tree-03",
      "file": "props/tree-03.png",
      "width": 68,
      "height": 88,
      "atlasRect": {
        "x": 354,
        "y": 0,
        "w": 68,
        "h": 88
      }
    },
    {
      "id": "tree-04",
      "file": "props/tree-04.png",
      "width": 50,
      "height": 90,
      "atlasRect": {
        "x": 426,
        "y": 0,
        "w": 50,
        "h": 90
      }
    },
    {
      "id": "tree-05",
      "file": "props/tree-05.png",
      "width": 68,
      "height": 88,
      "atlasRect": {
        "x": 0,
        "y": 156,
        "w": 68,
        "h": 88
      }
    },
    {
      "id": "tree-06",
      "file": "props/tree-06.png",
      "width": 68,
      "height": 88,
      "atlasRect": {
        "x": 72,
        "y": 156,
        "w": 68,
        "h": 88
      }
    },
    {
      "id": "tree-07",
      "file": "props/tree-07.png",
      "width": 68,
      "height": 88,
      "atlasRect": {
        "x": 198,
        "y": 156,
        "w": 68,
        "h": 88
      }
    },
    {
      "id": "tree-08",
      "file": "props/tree-08.png",
      "width": 50,
      "height": 90,
      "atlasRect": {
        "x": 270,
        "y": 156,
        "w": 50,
        "h": 90
      }
    },
    {
      "id": "tree-09",
      "file": "props/tree-09.png",
      "width": 68,
      "height": 88,
      "atlasRect": {
        "x": 0,
        "y": 250,
        "w": 68,
        "h": 88
      }
    },
    {
      "id": "tree-10",
      "file": "props/tree-10.png",
      "width": 68,
      "height": 88,
      "atlasRect": {
        "x": 198,
        "y": 250,
        "w": 68,
        "h": 88
      }
    },
    {
      "id": "bush-01",
      "file": "props/bush-01.png",
      "width": 38,
      "height": 28,
      "atlasRect": {
        "x": 342,
        "y": 250,
        "w": 38,
        "h": 28
      }
    },
    {
      "id": "bench-01",
      "file": "props/bench-01.png",
      "width": 60,
      "height": 40,
      "atlasRect": {
        "x": 84,
        "y": 344,
        "w": 60,
        "h": 40
      }
    },
    {
      "id": "flowerbed-01",
      "file": "props/flowerbed-01.png",
      "width": 46,
      "height": 44,
      "atlasRect": {
        "x": 212,
        "y": 344,
        "w": 46,
        "h": 44
      }
    },
    {
      "id": "flowerbed-02",
      "file": "props/flowerbed-02.png",
      "width": 58,
      "height": 48,
      "atlasRect": {
        "x": 262,
        "y": 344,
        "w": 58,
        "h": 48
      }
    },
    {
      "id": "flowerbed-03",
      "file": "props/flowerbed-03.png",
      "width": 60,
      "height": 48,
      "atlasRect": {
        "x": 324,
        "y": 344,
        "w": 60,
        "h": 48
      }
    },
    {
      "id": "sign-01",
      "file": "props/sign-01.png",
      "width": 42,
      "height": 54,
      "atlasRect": {
        "x": 388,
        "y": 344,
        "w": 42,
        "h": 54
      }
    },
    {
      "id": "sign-02",
      "file": "props/sign-02.png",
      "width": 42,
      "height": 54,
      "atlasRect": {
        "x": 434,
        "y": 344,
        "w": 42,
        "h": 54
      }
    },
    {
      "id": "water-bowl-01",
      "file": "props/water-bowl-01.png",
      "width": 24,
      "height": 16,
      "atlasRect": {
        "x": 480,
        "y": 344,
        "w": 24,
        "h": 16
      }
    },
    {
      "id": "fence-01",
      "file": "props/fence-01.png",
      "width": 32,
      "height": 26,
      "atlasRect": {
        "x": 56,
        "y": 402,
        "w": 32,
        "h": 26
      }
    },
    {
      "id": "fence-02",
      "file": "props/fence-02.png",
      "width": 32,
      "height": 26,
      "atlasRect": {
        "x": 128,
        "y": 402,
        "w": 32,
        "h": 26
      }
    },
    {
      "id": "bridge-01",
      "file": "props/bridge-01.png",
      "width": 88,
      "height": 58,
      "bakedIntoGround": true
    },
    {
      "id": "bridge-02",
      "file": "props/bridge-02.png",
      "width": 74,
      "height": 52,
      "bakedIntoGround": true
    }
  ],
  "preview": "preview.html",
  "originalAssetsOnly": true
};
export const mapLayout = layout;
