// AUTO-GENERATED by scripts/gen-map-assets — do not hand-edit. Re-run after asset changes.
import layout from './02-woodland-trail/map/layout.json';

export const groundImage = require('./02-woodland-trail/map/ground.png');
export const waterFullMapFrames = [
  require('./02-woodland-trail/animations/water/full-map/frame-00.png'),
  require('./02-woodland-trail/animations/water/full-map/frame-01.png'),
  require('./02-woodland-trail/animations/water/full-map/frame-02.png'),
  require('./02-woodland-trail/animations/water/full-map/frame-03.png'),
  require('./02-woodland-trail/animations/water/full-map/frame-04.png'),
  require('./02-woodland-trail/animations/water/full-map/frame-05.png'),
  require('./02-woodland-trail/animations/water/full-map/frame-06.png'),
  require('./02-woodland-trail/animations/water/full-map/frame-07.png'),
];
export const grassSheet = require('./02-woodland-trail/animations/grass/sheet.png');
export const reedsSheet = require('./02-woodland-trail/animations/reeds/sheet.png');

export const propImages: Record<string, number> = {
  'cottage-01': require('./02-woodland-trail/props/cottage-01.png'),
  'cottage-02': require('./02-woodland-trail/props/cottage-02.png'),
  'tree-01': require('./02-woodland-trail/props/tree-01.png'),
  'tree-02': require('./02-woodland-trail/props/tree-02.png'),
  'tree-03': require('./02-woodland-trail/props/tree-03.png'),
  'tree-04': require('./02-woodland-trail/props/tree-04.png'),
  'tree-05': require('./02-woodland-trail/props/tree-05.png'),
  'tree-06': require('./02-woodland-trail/props/tree-06.png'),
  'tree-07': require('./02-woodland-trail/props/tree-07.png'),
  'tree-08': require('./02-woodland-trail/props/tree-08.png'),
  'tree-09': require('./02-woodland-trail/props/tree-09.png'),
  'tree-10': require('./02-woodland-trail/props/tree-10.png'),
  'tree-11': require('./02-woodland-trail/props/tree-11.png'),
  'tree-12': require('./02-woodland-trail/props/tree-12.png'),
  'tree-13': require('./02-woodland-trail/props/tree-13.png'),
  'tree-14': require('./02-woodland-trail/props/tree-14.png'),
  'bush-01': require('./02-woodland-trail/props/bush-01.png'),
  'bench-01': require('./02-woodland-trail/props/bench-01.png'),
  'flowerbed-01': require('./02-woodland-trail/props/flowerbed-01.png'),
  'flowerbed-02': require('./02-woodland-trail/props/flowerbed-02.png'),
  'sign-01': require('./02-woodland-trail/props/sign-01.png'),
  'water-bowl-01': require('./02-woodland-trail/props/water-bowl-01.png'),
  'fence-01': require('./02-woodland-trail/props/fence-01.png'),
  'fence-02': require('./02-woodland-trail/props/fence-02.png'),
  'bridge-01': require('./02-woodland-trail/props/bridge-01.png'),
  'bridge-02': require('./02-woodland-trail/props/bridge-02.png'),
};

export const mapManifest = {
  "name": "02-woodland-trail",
  "title": "숲속 산책길",
  "version": "1.0.0",
  "mapWidth": 640,
  "mapHeight": 640,
  "coordinates": "top-left, world pixels, y increases down",
  "pixelScale": 2,
  "sampling": "nearest",
  "layout": "map/layout.json",
  "ground": "map/ground.png",
  "sceneryAtlas": "map/scenery-atlas.png",
  "plantsAtlas": "animations/plants-atlas.png",
  "tilemap": "map/ground-tilemap.json",
  "drawOrder": [
    "ground",
    "masked water",
    "plants",
    "objects and actors sorted by depth",
    "labels and UI"
  ],
  "animations": {
    "water": {
      "frameWidth": 32,
      "frameHeight": 32,
      "frameCount": 8,
      "frameDurationMs": 250,
      "row": 0,
      "direction": "right",
      "sheet": "animations/water/sheet.png",
      "mask": "map/water-mask.png",
      "fullMapFrames": [
        "animations/water/full-map/frame-00.png",
        "animations/water/full-map/frame-01.png",
        "animations/water/full-map/frame-02.png",
        "animations/water/full-map/frame-03.png",
        "animations/water/full-map/frame-04.png",
        "animations/water/full-map/frame-05.png",
        "animations/water/full-map/frame-06.png",
        "animations/water/full-map/frame-07.png"
      ]
    },
    "grass": {
      "frameWidth": 24,
      "frameHeight": 24,
      "frameCount": 8,
      "frameDurationMs": 250,
      "row": 0,
      "anchorX": 12,
      "anchorY": 20,
      "sheet": "animations/grass/sheet.png",
      "combinedAtlasRow": 0
    },
    "reeds": {
      "frameWidth": 24,
      "frameHeight": 24,
      "frameCount": 8,
      "frameDurationMs": 250,
      "row": 0,
      "anchorX": 12,
      "anchorY": 20,
      "sheet": "animations/reeds/sheet.png",
      "combinedAtlasRow": 1
    }
  },
  "props": [
    {
      "id": "cottage-01",
      "file": "props/cottage-01.png",
      "width": 76,
      "height": 88,
      "atlasRect": {
        "x": 0,
        "y": 0,
        "w": 76,
        "h": 88
      }
    },
    {
      "id": "cottage-02",
      "file": "props/cottage-02.png",
      "width": 76,
      "height": 88,
      "atlasRect": {
        "x": 80,
        "y": 0,
        "w": 76,
        "h": 88
      }
    },
    {
      "id": "tree-01",
      "file": "props/tree-01.png",
      "width": 68,
      "height": 88,
      "atlasRect": {
        "x": 160,
        "y": 0,
        "w": 68,
        "h": 88
      }
    },
    {
      "id": "tree-02",
      "file": "props/tree-02.png",
      "width": 68,
      "height": 88,
      "atlasRect": {
        "x": 232,
        "y": 0,
        "w": 68,
        "h": 88
      }
    },
    {
      "id": "tree-03",
      "file": "props/tree-03.png",
      "width": 50,
      "height": 90,
      "atlasRect": {
        "x": 304,
        "y": 0,
        "w": 50,
        "h": 90
      }
    },
    {
      "id": "tree-04",
      "file": "props/tree-04.png",
      "width": 68,
      "height": 88,
      "atlasRect": {
        "x": 358,
        "y": 0,
        "w": 68,
        "h": 88
      }
    },
    {
      "id": "tree-05",
      "file": "props/tree-05.png",
      "width": 68,
      "height": 88,
      "atlasRect": {
        "x": 430,
        "y": 0,
        "w": 68,
        "h": 88
      }
    },
    {
      "id": "tree-06",
      "file": "props/tree-06.png",
      "width": 50,
      "height": 90,
      "atlasRect": {
        "x": 0,
        "y": 94,
        "w": 50,
        "h": 90
      }
    },
    {
      "id": "tree-07",
      "file": "props/tree-07.png",
      "width": 68,
      "height": 88,
      "atlasRect": {
        "x": 54,
        "y": 94,
        "w": 68,
        "h": 88
      }
    },
    {
      "id": "tree-08",
      "file": "props/tree-08.png",
      "width": 50,
      "height": 90,
      "atlasRect": {
        "x": 126,
        "y": 94,
        "w": 50,
        "h": 90
      }
    },
    {
      "id": "tree-09",
      "file": "props/tree-09.png",
      "width": 68,
      "height": 88,
      "atlasRect": {
        "x": 180,
        "y": 94,
        "w": 68,
        "h": 88
      }
    },
    {
      "id": "tree-10",
      "file": "props/tree-10.png",
      "width": 68,
      "height": 88,
      "atlasRect": {
        "x": 378,
        "y": 94,
        "w": 68,
        "h": 88
      }
    },
    {
      "id": "tree-11",
      "file": "props/tree-11.png",
      "width": 68,
      "height": 88,
      "atlasRect": {
        "x": 126,
        "y": 188,
        "w": 68,
        "h": 88
      }
    },
    {
      "id": "tree-12",
      "file": "props/tree-12.png",
      "width": 68,
      "height": 88,
      "atlasRect": {
        "x": 198,
        "y": 282,
        "w": 68,
        "h": 88
      }
    },
    {
      "id": "tree-13",
      "file": "props/tree-13.png",
      "width": 50,
      "height": 90,
      "atlasRect": {
        "x": 270,
        "y": 282,
        "w": 50,
        "h": 90
      }
    },
    {
      "id": "tree-14",
      "file": "props/tree-14.png",
      "width": 68,
      "height": 88,
      "atlasRect": {
        "x": 378,
        "y": 282,
        "w": 68,
        "h": 88
      }
    },
    {
      "id": "bush-01",
      "file": "props/bush-01.png",
      "width": 38,
      "height": 28,
      "atlasRect": {
        "x": 126,
        "y": 376,
        "w": 38,
        "h": 28
      }
    },
    {
      "id": "bench-01",
      "file": "props/bench-01.png",
      "width": 60,
      "height": 40,
      "atlasRect": {
        "x": 378,
        "y": 376,
        "w": 60,
        "h": 40
      }
    },
    {
      "id": "flowerbed-01",
      "file": "props/flowerbed-01.png",
      "width": 58,
      "height": 48,
      "atlasRect": {
        "x": 0,
        "y": 470,
        "w": 58,
        "h": 48
      }
    },
    {
      "id": "flowerbed-02",
      "file": "props/flowerbed-02.png",
      "width": 46,
      "height": 44,
      "atlasRect": {
        "x": 62,
        "y": 470,
        "w": 46,
        "h": 44
      }
    },
    {
      "id": "sign-01",
      "file": "props/sign-01.png",
      "width": 42,
      "height": 54,
      "atlasRect": {
        "x": 112,
        "y": 470,
        "w": 42,
        "h": 54
      }
    },
    {
      "id": "water-bowl-01",
      "file": "props/water-bowl-01.png",
      "width": 24,
      "height": 16,
      "atlasRect": {
        "x": 204,
        "y": 470,
        "w": 24,
        "h": 16
      }
    },
    {
      "id": "fence-01",
      "file": "props/fence-01.png",
      "width": 32,
      "height": 26,
      "atlasRect": {
        "x": 260,
        "y": 470,
        "w": 32,
        "h": 26
      }
    },
    {
      "id": "fence-02",
      "file": "props/fence-02.png",
      "width": 32,
      "height": 26,
      "atlasRect": {
        "x": 296,
        "y": 470,
        "w": 32,
        "h": 26
      }
    },
    {
      "id": "bridge-01",
      "file": "props/bridge-01.png",
      "width": 58,
      "height": 84,
      "bakedIntoGround": true
    },
    {
      "id": "bridge-02",
      "file": "props/bridge-02.png",
      "width": 58,
      "height": 82,
      "bakedIntoGround": true
    }
  ],
  "preview": "preview.html",
  "originalAssetsOnly": true
};
export const mapLayout = layout;
